# database init, supports mysql too
database: h2
#spring.sql.init.data-locations: "classpath*:db/${database}/data.sql"

# Liquibase - We want to run our own instance of liquibase, not spring autoconfigured one
spring.liquibase.enabled: false

# Web
spring.thymeleaf.mode: HTML

# JPA
spring.jpa.hibernate.ddl-auto: none
spring.jpa.open-in-view: true

# Internationalization
spring.messages.basename: messages/messages

# Actuator
management.endpoints.web.exposure.include: "*"

# Logging
logging.level.org.springframework: INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age: 12h
