# database init
database: h2
spring:
  datasource:
    url: jdbc:h2:tcp://localhost:4000/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false # Liquibase - We want to run our own instance of liquibase, not spring autoconfigured one

# Web
spring.thymeleaf.mode: HTML

# JPA
spring.jpa.hibernate.ddl-auto: none
spring.jpa.open-in-view: true

# Internationalization
spring.messages.basename: messages/messages

# Actuator
management.endpoints.web.exposure.include: "*"

# Logging
logging.level.org.springframework: INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age: 12h
